// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package thingmodel

import (
	context "context"
	drivercommon "github.com/zdglf/edge-driver-proto/drivercommon"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ThingModelUpServiceClient is the client API for ThingModelUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThingModelUpServiceClient interface {
	ThingModelMsgReport(ctx context.Context, in *ThingModelMsg, opts ...grpc.CallOption) (*drivercommon.CommonResponse, error)
}

type thingModelUpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThingModelUpServiceClient(cc grpc.ClientConnInterface) ThingModelUpServiceClient {
	return &thingModelUpServiceClient{cc}
}

func (c *thingModelUpServiceClient) ThingModelMsgReport(ctx context.Context, in *ThingModelMsg, opts ...grpc.CallOption) (*drivercommon.CommonResponse, error) {
	out := new(drivercommon.CommonResponse)
	err := c.cc.Invoke(ctx, "/thingmodel.ThingModelUpService/ThingModelMsgReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThingModelUpServiceServer is the server API for ThingModelUpService service.
// All implementations must embed UnimplementedThingModelUpServiceServer
// for forward compatibility
type ThingModelUpServiceServer interface {
	ThingModelMsgReport(context.Context, *ThingModelMsg) (*drivercommon.CommonResponse, error)
	mustEmbedUnimplementedThingModelUpServiceServer()
}

// UnimplementedThingModelUpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedThingModelUpServiceServer struct {
}

func (UnimplementedThingModelUpServiceServer) ThingModelMsgReport(context.Context, *ThingModelMsg) (*drivercommon.CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThingModelMsgReport not implemented")
}
func (UnimplementedThingModelUpServiceServer) mustEmbedUnimplementedThingModelUpServiceServer() {}

// UnsafeThingModelUpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThingModelUpServiceServer will
// result in compilation errors.
type UnsafeThingModelUpServiceServer interface {
	mustEmbedUnimplementedThingModelUpServiceServer()
}

func RegisterThingModelUpServiceServer(s grpc.ServiceRegistrar, srv ThingModelUpServiceServer) {
	s.RegisterService(&ThingModelUpService_ServiceDesc, srv)
}

func _ThingModelUpService_ThingModelMsgReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingModelMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingModelUpServiceServer).ThingModelMsgReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thingmodel.ThingModelUpService/ThingModelMsgReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingModelUpServiceServer).ThingModelMsgReport(ctx, req.(*ThingModelMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// ThingModelUpService_ServiceDesc is the grpc.ServiceDesc for ThingModelUpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThingModelUpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thingmodel.ThingModelUpService",
	HandlerType: (*ThingModelUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ThingModelMsgReport",
			Handler:    _ThingModelUpService_ThingModelMsgReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thingmodel/thingmodel.proto",
}

// ThingModelDownServiceClient is the client API for ThingModelDownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThingModelDownServiceClient interface {
	ThingModelMsgIssue(ctx context.Context, in *ThingModelIssueMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type thingModelDownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThingModelDownServiceClient(cc grpc.ClientConnInterface) ThingModelDownServiceClient {
	return &thingModelDownServiceClient{cc}
}

func (c *thingModelDownServiceClient) ThingModelMsgIssue(ctx context.Context, in *ThingModelIssueMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/thingmodel.ThingModelDownService/ThingModelMsgIssue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThingModelDownServiceServer is the server API for ThingModelDownService service.
// All implementations must embed UnimplementedThingModelDownServiceServer
// for forward compatibility
type ThingModelDownServiceServer interface {
	ThingModelMsgIssue(context.Context, *ThingModelIssueMsg) (*emptypb.Empty, error)
	mustEmbedUnimplementedThingModelDownServiceServer()
}

// UnimplementedThingModelDownServiceServer must be embedded to have forward compatible implementations.
type UnimplementedThingModelDownServiceServer struct {
}

func (UnimplementedThingModelDownServiceServer) ThingModelMsgIssue(context.Context, *ThingModelIssueMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThingModelMsgIssue not implemented")
}
func (UnimplementedThingModelDownServiceServer) mustEmbedUnimplementedThingModelDownServiceServer() {}

// UnsafeThingModelDownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThingModelDownServiceServer will
// result in compilation errors.
type UnsafeThingModelDownServiceServer interface {
	mustEmbedUnimplementedThingModelDownServiceServer()
}

func RegisterThingModelDownServiceServer(s grpc.ServiceRegistrar, srv ThingModelDownServiceServer) {
	s.RegisterService(&ThingModelDownService_ServiceDesc, srv)
}

func _ThingModelDownService_ThingModelMsgIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThingModelIssueMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThingModelDownServiceServer).ThingModelMsgIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thingmodel.ThingModelDownService/ThingModelMsgIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThingModelDownServiceServer).ThingModelMsgIssue(ctx, req.(*ThingModelIssueMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// ThingModelDownService_ServiceDesc is the grpc.ServiceDesc for ThingModelDownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThingModelDownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thingmodel.ThingModelDownService",
	HandlerType: (*ThingModelDownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ThingModelMsgIssue",
			Handler:    _ThingModelDownService_ThingModelMsgIssue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thingmodel/thingmodel.proto",
}
